language: python
python:
- '3.8'
- '3.9'
install:
- pip install .
script:
- python -m unittest discover -v
- make -C docs/ html
- touch docs/build/html/.nojekyll
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    egde: true
    local_dir: ./docs/build/html/
    keep_history: true
