package:
    name: bioimagepy
    version: 0.1.0

source:
    git_url: https://gitlab.inria.fr/sprigent1/bioimagepy-tutorial.git
    git_rev: master

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

about:
    home: https://gitlab.inria.fr/sprigent1/bioimagepy-tutorial
    license: unknown
    summary: "Python library for bio-image metadata maniplation"
